stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: node:14 # Use Node.js image for running tests
  script:
    - npm install # Install dependencies
    - npm test # Run Jest tests with JSDOM environment

build:
  stage: build
  image: docker:latest # Use Docker image for building Docker images
  services:
    - docker:dind # Enable Docker service inside the Docker container
  script:
    - docker build -t tree-drawer . # Build Docker image
    - docker tag tree-drawer:latest gendiro/tree-drawer # Tag Docker image
    - docker push gendiro/tree-drawer # Push Docker image to registry

deploy:
  stage: deploy
  image: docker:latest # Use Docker image for deploying Docker images
  services:
    - docker:dind # Enable Docker service inside the Docker container
  script:
    - docker run -d -p 80:80 --name tree-drawer-container tree-drawer:latest # Run Docker container

